### ISSUE TITLE
Extremely poor performance on windows

### ISSUE THREAD

**Issue by richard-broadhurst** [tom-seddon/b2#6] opened 2018-04-11 08:27 UTC
I've just tried the v0.0.4 prebuilt release version on windows7x64 on a Core2 Quad and although the emulated beeb seems to be running fine (~1X), the menu and screen updates are less than 1 fps.
The emulator takes over 30 seconds to start up, but only uses 3-5% CPU - it is using the DX renderer.

**Comment by tom-seddon** [comment] 2018-04-11 13:42
Ugh, sorry about that. I don't have Windows 7 to test with either :(

I wonder if this is Windows 7 not supporting the vsync callback that b2 uses... I probably need to add the option in to make it do screen updates on a timer instead.

Meanwhile, does it make a difference if you try one of the other renderers? Run b2.exe from the command line with `b2 --help` - if multiple renderers are available, the help output will have an entry for `-r`, and a list of the renderers available. If available, does using the other renderers make a difference?

Thanks,

--Tom

**Comment by richard-broadhurst** [comment] 2018-04-11 18:35
The opengl DRIVER behaves the same behaviour as direct3d, 30+ seconds to start up, poor display rate.
-r direct3d11 and opengles2 both crash b2, even though I have dx11!

**Comment by tom-seddon** [comment] 2018-04-15 00:28
I've pushed what is hopefully a workaround for this... if you've got a few minutes, you could try [building from source](https://github.com/tom-seddon/b2/blob/master/doc/Building-on-Windows.md), and then running with the new `--ignore-vblank` option. But if not, I'll do a new release in the next week or two anyway, since it's been a while since the last one.

--Tom

**Comment by richard-broadhurst** [comment] 2018-04-15 10:00
Thanks for taking the time to try this, it looks like b2 has some great
features.
I've never had any success with cmake or python, so if you don't mind, I'll
wait for next week.
Once cmake has been run, are you left with a visual studio project and
solution, if so, maybe you could include those with the source in future.
Richard

**Comment by tom-seddon** [comment] 2018-04-15 23:13
Due to the way cmake works, the projects it creates aren't distributable, I'm afraid :(

Each person has to use cmake to generate their own.

--Tom

**Comment by richard-broadhurst** [comment] 2018-04-17 17:32
Hi Tom,

The new build, b2-7855bbc-windows took 2 minutes 57 seconds to display the
window border and a further 20 seconds to put anything in it!
It has a message displayed:

object not found: shortcuts
array not found: popups
Renderer: direct3d, 736x576 SDL_PIXELFORMAT_ARGB8888
Sound: wasapi, 48000Hz 1-channel (4096 byte buffer)

It started its 15 threads and used 0% CPU for the 3 minutes.

It is showing ~1x, but is so slow that it is hard to type as you have to
hold the keys down for over a second and clicking the UI is as bad.

The game runs at normal speed, but it is still about 1fps.

Sorry.

**Comment by tom-seddon** [comment] 2018-04-17 17:43
Is this with `--ignore-vblank`?

--Tom

**Comment by tom-seddon** [comment] 2018-04-17 18:31
Ah, excellent! - thanks for that.

Looking at the code again, it looks like I'm missing an error check when waiting for the vblank - so maybe that's the problem, and the timing-based solution won't be necessary? Anyway, I'll put the error check in first - will post here again... - to see if that fixes it.

Thanks,

--Tom

**Comment by tom-seddon** [comment] 2018-05-10 00:54
I've added the missing error check. If the WaitForVBlank call fails, the emulator will switch to just updating at 50Hz. There should hopefully be an [AppVeyor build](https://ci.appveyor.com/project/tom-seddon/b2/history) for this commit by the time you read this - if you get a chance to try it, please let me know how you get on.

If this build works, I'll remove the annoying extra messages and that'll be the fix.

If it's still broken, I'll put in the fix you suggest. It should only need to wait for 100ms or something - if it hasn't got a vblank by then, something's obviously wrong!

--Tom

**Comment by richard-broadhurst** [comment] 2018-05-10 06:12
Still taking ages to start up - waited two minutes, but have to go to work;
will try again tonight.

**Comment by tom-seddon** [comment] 2018-05-10 09:13
Thanks for trying it. I'm not working this morning, so I'll get the alternative fix plumbed in now.

I've added the note about Frogger to #7. There's clearly something a bit wrong with the NuLA emulation.

--Tom

**Comment by tom-seddon** [comment] 2018-05-11 00:20
There should be another AppVeyor build ready soon with take 2 of a fix for this!

If it still doesn't work, please would you try running the debug version from the command line with the `-e vblank` option, and let me know what it prints? (It should print a bunch of stuff with `VBLANK` and `VBLMON` prefixes.)

This might help to narrow things down, or give me a clue what's going on...

Thanks,

--Tom

**Comment by tom-seddon** [comment] 2018-05-11 18:29
No command line switches should be necessary for normal use! Double click, and it should be ready for action within ~0.5 seconds.

Does it print anything if you run it from the command prompt with the `-e vblank` option?

I wonder now if maybe the problem is too many vblanks rather than too few, and it's getting swamped? So I might have another build for you to try at some point, if you're not sick of this.

--Tom

**Comment by richard-broadhurst** [comment] 2018-05-11 18:47
-e vblank doesn't print anything.
would too many vblanks cause no CPU utilisation?
I'm happy to keep trying.

**Comment by richard-broadhurst** [comment] 2018-05-11 18:49
If that option was for the debug build, it gives:
C:\DATA\BBC\Emulators\b2-windows-20180511-011541-b6de95d\b2>b2_Debug.exe -e
vblank
VBLANK: \\.\DISPLAY1: starting vblank thread.
VBLANK: \\.\DISPLAY4: starting vblank thread.
VBLMON: \\.\DISPLAY1: thread=000000000032C900, display=0000000001FFFF40
VBLMON: \\.\DISPLAY4: thread=000000000032C9F0, display=0000000001FF32A0
VBLMON: \\.\DISPLAY1: WaitForVBlank appears to be working. Monitor thread
will finish.
VBLMON: \\.\DISPLAY4: WaitForVBlank appears to be working. Monitor thread
will finish.

And starts withing about 15 seconds, but still doesn't run well.

**Comment by richard-broadhurst** [comment] 2018-05-11 18:57
Sorry, the text was from -e, but the startup was a b2 that I had started
before hibernating my PC and forgotten about.
When the emulator is closed, the last five lines are output:

C:\DATA\BBC\Emulators\b2-windows-20180511-011541-b6de95d\b2>b2_Debug.exe -e
vblank
VBLANK: \\.\DISPLAY1: starting vblank thread.
VBLANK: \\.\DISPLAY4: starting vblank thread.
VBLMON: \\.\DISPLAY1: thread=00000000003F8C20, display=0000000001FDC4A0
VBLMON: \\.\DISPLAY4: thread=00000000003F8D10, display=0000000001FDC8D0
VBLMON: \\.\DISPLAY4: WaitForVBlank appears to be working. Monitor thread
will finish.
VBLMON: \\.\DISPLAY1: WaitForVBlank appears to be working. Monitor thread
will finish.
[-AI] async    0000000003D2FB10
[RA-] tcp      0000000002005570
[RA-] async    000000000210D5E0
VBLANK: \\.\DISPLAY1: vblank thread will end. (display is NULL after
WaitForVBlank.)
VBLANK: \\.\DISPLAY4: vblank thread will end. (display is NULL after
WaitForVBlank.)

Is it trying to open two displays? I don't have a monitor on the second
screen at the moment.

**Comment by tom-seddon** [comment] 2018-05-12 23:07
Yes, sorry, you do need to use the debug version with the `-e` flag - my fault, I run the debug version about 100% of the time so I didn't think to mention it :(

Anyway, the output was a bit confusing, and clearly this isn't something obvious, so rather than do this over and over again, I've now installed Windows 7 on my desktop PC and reproduced the problem - or at least, one like it :)

So, fingers crossed, no need for any more back and fortha and there'll be some kind of fix for this coming...

--Tom

**Comment by tom-seddon** [comment] 2018-05-13 12:51
Fingers crossed, it should all now work out of the box.

--Tom

**Comment by richard-broadhurst** [comment] 2018-05-13 17:35
Sorry, b2-windows-20180513-134850-b238605 (hope that's the correct version)
still takes over two minutes to start and still has poor frame rate.

**Closed** 2018-05-20 23:50 UTC
